title: Herisatry
description: "A diary of my data analysis and cybersec journey"
author:
  name: "Herisatry"
  email: "herisatry@gmail.com"
  url: 

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "herisatry"
year : "2024"
